// Generated by assets/source/dressers-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "dresser-11-nord-door-four-drawer",
  "label": "Комод «Норд»",
  "modelUrl": "/models/dresser-11-nord-door-four-drawer.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 1.2,
      "min": 1,
      "max": 1.6,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 0.9,
      "min": 0.75,
      "max": 1.1,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.45,
      "min": 0.35,
      "max": 0.6,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Door_Left_Hinge",
      "target": "Door_Left_Hinge",
      "label": "Левая дверь",
      "kind": "door",
      "angle": -105
    },
    {
      "id": "Drawer_04_Assembly",
      "target": "Drawer_04_Assembly",
      "label": "Ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.398,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_03_Assembly",
      "target": "Drawer_03_Assembly",
      "label": "Ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.398,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_02_Assembly",
      "target": "Drawer_02_Assembly",
      "label": "Ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.398,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_01_Assembly",
      "target": "Drawer_01_Assembly",
      "label": "Ящик 4 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.398,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    }
  ],
  "category": "dressers",
  "description": "Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.",
  "framing": {
    "width": 1.6,
    "height": 1.1,
    "depth": 0.6
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и внутренние детали",
      "targets": [],
      "defaultFinish": "board-cashmere-body",
      "allowedFinishes": [
        "board-cashmere-body",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-cashmere-front",
      "allowedFinishes": [
        "board-cashmere-front",
        "board-white-gloss",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "hardware": {
      "label": "Ручки",
      "targets": [],
      "defaultFinish": "metal-brass-satin",
      "allowedFinishes": [
        "metal-brass-satin",
        "metal-black-matte",
        "metal-white-matte",
        "metal-anthracite"
      ]
    }
  },
  "facades": {
    "defaultStyle": "smooth",
    "styles": [
      "smooth",
      "frame",
      "fluted",
      "fluted-sides",
      "diagonal",
      "herringbone",
      "diamonds"
    ],
    "targets": [
      {
        "panel": "Door_Left_Front",
        "width": {
          "base": 0.395,
          "dimension": "width",
          "factor": 0.33333333333333337
        },
        "height": {
          "base": 0.852,
          "dimension": "height",
          "factor": 1
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_01_Front",
        "width": {
          "base": 0.795,
          "dimension": "width",
          "factor": 0.6666666666666666
        },
        "height": {
          "base": 0.1995,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_02_Front",
        "width": {
          "base": 0.795,
          "dimension": "width",
          "factor": 0.6666666666666666
        },
        "height": {
          "base": 0.1995,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_03_Front",
        "width": {
          "base": 0.795,
          "dimension": "width",
          "factor": 0.6666666666666666
        },
        "height": {
          "base": 0.1995,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_04_Front",
        "width": {
          "base": 0.795,
          "dimension": "width",
          "factor": 0.6666666666666666
        },
        "height": {
          "base": 0.1995,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      }
    ],
    "materialSlot": "fronts",
    "bevel": 0.0007,
    "frame": {
      "width": 0.028,
      "depth": 0.003,
      "slope": 0.002,
      "minField": 0.04
    },
    "fluted": {
      "pitch": 0.02,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "fade": 0.003
    },
    "sourceStyle": "smooth",
    "diagonal": {
      "pitch": 0.08,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "minLength": 0.024
    },
    "herringbone": {
      "pitch": 0.08,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "minLength": 0.024,
      "centerGap": 0.012
    },
    "diamonds": {
      "pitch": 0.08,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "fade": 0.006
    },
    "styleFallbacks": {
      "herringbone-wide": "herringbone"
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
