"""Generate lazy production definitions without changing the model author's review configs.
Run after rebuilding the GLBs: python assets/source/dressers-integration/generate_runtime.py
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[3]
MODELS = [
    ('10', 'dresser-white-four-drawer', 'dresser-10-white-four-drawer', 'board-white-alaska-body', 'board-white-alaska-front', None),
    ('11', 'dresser-nord-door-four-drawer', 'dresser-11-nord-door-four-drawer', 'board-cashmere-body', 'board-cashmere-front', 'metal-brass-satin'),
    ('12', 'dresser-brooklyn-six-drawer', 'dresser-12-brooklyn-six-drawer', 'board-white-brooklyn-body', 'board-white-gloss', 'metal-white-matte'),
    ('13', 'dresser-marvel-fluted', 'dresser-13-marvel-fluted', 'oak-natural', 'board-white-brush', 'metal-black-matte'),
    ('14', 'dresser-baikal-five-drawer', 'dresser-14-baikal-five-drawer', 'oak-natural', 'board-white-baikal', 'metal-black-matte'),
]
COMMON = ['board-white-matte', 'board-grey-neutral', 'board-graphite-matte',
          'oak-natural', 'oak-grey', 'oak-silver', 'oak-black']
HARDWARE = ['metal-black-matte', 'metal-white-matte', 'metal-anthracite', 'metal-brass-satin']


def slot(label, default, candidates):
    return dict(label=label, targets=[], defaultFinish=default,
                allowedFinishes=list(dict.fromkeys([default, *candidates])))


for number, folder, model_id, body, front, hardware in MODELS:
    target = ROOT / 'src/three/models' / folder
    source = (target / 'config.ts').read_text(encoding='utf-8')
    config = json.loads(re.search(r'export const DRESSER_\d+_CONFIG = (\{.*?\}) as const satisfies', source, re.S)[1])
    contract = json.loads((ROOT / 'assets/source' / model_id / 'model-contract.json').read_text(encoding='utf-8'))
    for dimension in config['dimensions'].values():
        dimension['displayUnit'] = 'mm'
    slots = dict(
        carcass=slot('Корпус и внутренние детали', body, ['board-cashmere-body', *COMMON]),
        fronts=slot('Фасады', front, ['board-white-gloss', 'board-cashmere-front', *COMMON]),
    )
    if body == 'oak-natural':
        # Match the author's smoother laminated oak while reusing all shared maps.
        slots['carcass']['finishOverrides'] = {'oak-natural': {'normalScale': 0.2}}
    if hardware:
        slots['hardware'] = slot('Ручки', hardware, HARDWARE)
    metadata = {key: config[key] for key in ['id', 'label', 'modelUrl', 'dimensions', 'dimensionOrder']}
    metadata.update(
        category='dressers', description='Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.',
        framing={axis: config['dimensions'][axis]['max'] for axis in ['width', 'height', 'depth']},
        resizeRules=[], textureAxes={}, materialSlots=slots,
    )
    (target / 'catalog.ts').write_text(
        "// Generated by assets/source/dressers-integration/generate_runtime.py\n"
        "import type { FurnitureDefinition } from '../../furniture/types'\n\n"
        "export const catalogue: FurnitureDefinition = {\n  ..." + json.dumps(metadata, ensure_ascii=False, indent=2) +
        ",\n  loadRuntime: () => import('./runtime').then(module => module.definition),\n}\n", encoding='utf-8')
    bindings = {name: {axis: {k: v for k, v in binding.items() if k != 'axis'}
                     for axis, binding in data['bindings'].items()}
                for name, data in contract['uvContract'].items()}
    (target / 'textureTransforms.ts').write_text(
        "// Generated from model-contract.json; preserve physical texture size and seam phase.\n"
        "import type { FurnitureDefinition } from '../../furniture/types'\n"
        "export const textureTransforms = " + json.dumps(bindings, indent=2) +
        " as const satisfies NonNullable<FurnitureDefinition['textureTransforms']>\n", encoding='utf-8')
    slot_lines = '\n'.join(f'    {key}: {{ ...catalogue.materialSlots!.{key}, targets: MATERIAL_TARGETS.{key} }},' for key in slots)
    (target / 'runtime.ts').write_text(f"""// Generated production integration; keep original model review config reproducible.
import type {{ FurnitureDefinition }} from '../../furniture/types'
import {{ DRESSER_{number}_CONFIG as source, MATERIAL_TARGETS }} from './config'
import {{ catalogue }} from './catalog'
import {{ textureTransforms }} from './textureTransforms'

export const definition: FurnitureDefinition = {{
  ...catalogue, loadRuntime: undefined,
  resizeRules: source.resizeRules, textureTransforms,
  materialSlots: {{
{slot_lines}
  }},
}}
""", encoding='utf-8')
print('Generated five lazy dresser catalogue and runtime definitions.')
