"""Build light catalogue entries and lazy runtime definitions from reviewed source contracts.
Run from any directory: python assets/source/wardrobes-integration/generate_runtime.py
Original model generators and their review configs remain reproducible and unchanged.
"""
from pathlib import Path
import json, re
ROOT = Path(__file__).resolve().parents[3]
MODELS = [
 ('07', 'wardrobe-center-drawers', 'wardrobe-07-center-drawers', 'board-grey-neutral'),
 ('08', 'wardrobe-four-door', 'wardrobe-08-four-door', 'board-grey-cool'),
 ('09', 'wardrobe-chelsea-two-door', 'wardrobe-09-chelsea-two-door', 'board-grey-chelsea'),
]
FINISHES = ['board-grey-neutral', 'board-grey-cool', 'board-grey-chelsea', 'board-white-matte',
 'board-graphite-matte', 'oak-natural', 'oak-grey', 'oak-silver', 'oak-black']
def write(path, content):
 path.write_text(content, encoding='utf-8')

for number, folder, model_id, finish in MODELS:
 target = ROOT / 'src/three/models' / folder
 source = (target / 'config.ts').read_text(encoding='utf-8')
 config = json.loads(re.search(r'export const WARDROBE_\d+_CONFIG = (\{.*?\}) as const satisfies', source, re.S)[1])
 contract = json.loads((ROOT / 'assets/source' / model_id / 'model-contract.json').read_text(encoding='utf-8'))
 for dimension in config['dimensions'].values(): dimension['displayUnit'] = 'mm'
 metadata = {key: config[key] for key in ['id', 'label', 'modelUrl', 'dimensions', 'dimensionOrder']}
 metadata.update(category='wardrobes', description='Размеры корпуса меняются с сохранением толщины панелей.',
  interiorView={'hiddenNodes': [door['name'] for door in contract['doors']]},
  framing={axis: config['dimensions'][dimension]['max'] for axis, dimension in [('width','width'),('height','height'),('depth','depth')]},
  resizeRules=[], textureAxes={}, materialSlots={
   'carcass': dict(label='Корпус и полки', targets=[], defaultFinish=finish, allowedFinishes=FINISHES),
   'fronts': dict(label='Фасады', targets=[], defaultFinish=finish, allowedFinishes=FINISHES),
   **{key: {**value, 'targets': []} for key, value in config['materialSlots'].items()}
  })
 write(target / 'catalog.ts', "// Generated by assets/source/wardrobes-integration/generate_runtime.py\nimport type { FurnitureDefinition } from '../../furniture/types'\n\nexport const catalogue: FurnitureDefinition = {\n  ..."+json.dumps(metadata, ensure_ascii=False, indent=2)+",\n  loadRuntime: () => import('./runtime').then(module => module.definition),\n}\n")
 bindings={name: {axis: {k:v for k,v in binding.items() if k != 'axis'} for axis,binding in data['bindings'].items()} for name,data in contract['uvContract'].items()}
 write(target / 'textureTransforms.ts', "// Generated from model-contract.json; UV units/metre and segment anchors are preserved.\nimport type { FurnitureDefinition } from '../../furniture/types'\nexport const textureTransforms = "+json.dumps(bindings, ensure_ascii=False, indent=2)+" as const satisfies NonNullable<FurnitureDefinition['textureTransforms']>\n")
 write(target / 'runtime.ts', f"""// Generated production integration; the source config remains the original review definition.
import type {{ FurnitureDefinition }} from '../../furniture/types'
import {{ WARDROBE_{number}_CONFIG as source, BOARD_MATERIAL_TARGETS }} from './config'
import {{ catalogue }} from './catalog'
import {{ textureTransforms }} from './textureTransforms'

export const definition: FurnitureDefinition = {{
  ...catalogue, loadRuntime: undefined,
  resizeRules: source.resizeRules, textureTransforms,
  materialSlots: {{
    carcass: {{ ...catalogue.materialSlots!.carcass, targets: BOARD_MATERIAL_TARGETS.carcass }},
    fronts: {{ ...catalogue.materialSlots!.fronts, targets: BOARD_MATERIAL_TARGETS.fronts }},
    ...source.materialSlots,
  }},
}}
""")
print('Generated catalogue and runtime definitions for 3 wardrobes.')
