// Generated by assets/source/wardrobes-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "wardrobe-07-center-drawers",
  "label": "Шкаф с центральными ящиками",
  "modelUrl": "/models/wardrobe-07-center-drawers.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 1.601,
      "min": 1.4,
      "max": 2,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 2.052,
      "min": 1.9,
      "max": 2.4,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.48,
      "min": 0.4,
      "max": 0.65,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Door_Outer_Left_Hinge",
      "target": "Door_Outer_Left_Hinge",
      "label": "Левая крайняя дверь",
      "kind": "door",
      "angle": -105
    },
    {
      "id": "Door_Center_Left_Hinge",
      "target": "Door_Center_Left_Hinge",
      "label": "Левая центральная дверь",
      "kind": "door",
      "angle": -105
    },
    {
      "id": "Door_Center_Right_Hinge",
      "target": "Door_Center_Right_Hinge",
      "label": "Правая центральная дверь",
      "kind": "door",
      "angle": 105
    },
    {
      "id": "Door_Outer_Right_Hinge",
      "target": "Door_Outer_Right_Hinge",
      "label": "Правая крайняя дверь",
      "kind": "door",
      "angle": 105
    },
    {
      "id": "Drawer_03_Assembly",
      "target": "Drawer_03_Assembly",
      "label": "Ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.435,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_02_Assembly",
      "target": "Drawer_02_Assembly",
      "label": "Ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.435,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_01_Assembly",
      "target": "Drawer_01_Assembly",
      "label": "Ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.435,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    }
  ],
  "category": "wardrobes",
  "description": "Размеры корпуса меняются с сохранением толщины панелей.",
  "interiorView": {
    "hiddenNodes": [
      "Door_Outer_Left_Hinge",
      "Door_Center_Left_Hinge",
      "Door_Center_Right_Hinge",
      "Door_Outer_Right_Hinge"
    ]
  },
  "framing": {
    "width": 2,
    "height": 2.4,
    "depth": 0.65
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и полки",
      "targets": [],
      "defaultFinish": "board-grey-neutral",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-grey-neutral",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "hardware": {
      "label": "Цвет фурнитуры",
      "targets": [],
      "defaultFinish": "metal-black-matte",
      "allowedFinishes": [
        "metal-black-matte",
        "metal-white-matte",
        "metal-anthracite"
      ]
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
