// Generated by assets/source/dressers-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "dresser-10-white-four-drawer",
  "label": "Белый комод, 4 ящика",
  "modelUrl": "/models/dresser-10-white-four-drawer.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 0.7,
      "min": 0.5,
      "max": 1,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 0.856,
      "min": 0.7,
      "max": 1.05,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.35,
      "min": 0.3,
      "max": 0.5,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "category": "dressers",
  "description": "Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.",
  "framing": {
    "width": 1,
    "height": 1.05,
    "depth": 0.5
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и внутренние детали",
      "targets": [],
      "defaultFinish": "board-white-alaska-body",
      "allowedFinishes": [
        "board-white-alaska-body",
        "board-cashmere-body",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-white-alaska-front",
      "allowedFinishes": [
        "board-white-alaska-front",
        "board-white-gloss",
        "board-cashmere-front",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
