// Generated by assets/source/dressers-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "dresser-10-white-four-drawer",
  "label": "Белый комод, 4 ящика",
  "modelUrl": "/models/dresser-10-white-four-drawer.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 0.7,
      "min": 0.5,
      "max": 1,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 0.856,
      "min": 0.7,
      "max": 1.05,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.35,
      "min": 0.3,
      "max": 0.5,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Drawer_04_Assembly",
      "target": "Drawer_04_Assembly",
      "label": "Ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.31599999999999995,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_03_Assembly",
      "target": "Drawer_03_Assembly",
      "label": "Ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.31599999999999995,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_02_Assembly",
      "target": "Drawer_02_Assembly",
      "label": "Ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.31599999999999995,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_01_Assembly",
      "target": "Drawer_01_Assembly",
      "label": "Ящик 4 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.31599999999999995,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    }
  ],
  "category": "dressers",
  "description": "Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.",
  "framing": {
    "width": 1,
    "height": 1.05,
    "depth": 0.5
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и внутренние детали",
      "targets": [],
      "defaultFinish": "board-white-alaska-body",
      "allowedFinishes": [
        "board-white-alaska-body",
        "board-cashmere-body",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-white-alaska-front",
      "allowedFinishes": [
        "board-white-alaska-front",
        "board-white-gloss",
        "board-cashmere-front",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    }
  },
  "facades": {
    "defaultStyle": "smooth",
    "styles": [
      "smooth",
      "frame",
      "fluted",
      "fluted-sides"
    ],
    "targets": [
      {
        "panel": "Drawer_01_Front",
        "width": {
          "base": 0.692,
          "dimension": "width",
          "factor": 1
        },
        "height": {
          "base": 0.18925,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_02_Front",
        "width": {
          "base": 0.692,
          "dimension": "width",
          "factor": 1
        },
        "height": {
          "base": 0.18925,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_03_Front",
        "width": {
          "base": 0.692,
          "dimension": "width",
          "factor": 1
        },
        "height": {
          "base": 0.18925,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      },
      {
        "panel": "Drawer_04_Front",
        "width": {
          "base": 0.692,
          "dimension": "width",
          "factor": 1
        },
        "height": {
          "base": 0.18925,
          "dimension": "height",
          "factor": 0.25
        },
        "thickness": 0.016
      }
    ],
    "materialSlot": "fronts",
    "bevel": 0.0007,
    "frame": {
      "width": 0.028,
      "depth": 0.003,
      "slope": 0.002,
      "minField": 0.04
    },
    "fluted": {
      "pitch": 0.02,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "fade": 0.003
    },
    "sourceStyle": "smooth"
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
