// Generated by assets/source/dressers-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "dresser-14-baikal-five-drawer",
  "label": "Комод «Байкал»",
  "modelUrl": "/models/dresser-14-baikal-five-drawer.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 0.402,
      "min": 0.35,
      "max": 0.6,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 1.03,
      "min": 0.9,
      "max": 1.2,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.331,
      "min": 0.3,
      "max": 0.5,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Drawer_05_Assembly",
      "target": "Drawer_05_Assembly",
      "label": "Ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.277,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_04_Assembly",
      "target": "Drawer_04_Assembly",
      "label": "Ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.277,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_03_Assembly",
      "target": "Drawer_03_Assembly",
      "label": "Ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.277,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_02_Assembly",
      "target": "Drawer_02_Assembly",
      "label": "Ящик 4 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.277,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_01_Assembly",
      "target": "Drawer_01_Assembly",
      "label": "Ящик 5 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.277,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    }
  ],
  "category": "dressers",
  "description": "Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.",
  "framing": {
    "width": 0.6,
    "height": 1.2,
    "depth": 0.5
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и внутренние детали",
      "targets": [],
      "defaultFinish": "oak-natural",
      "allowedFinishes": [
        "oak-natural",
        "board-cashmere-body",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ],
      "finishOverrides": {
        "oak-natural": {
          "normalScale": 0.2
        }
      }
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-white-baikal",
      "allowedFinishes": [
        "board-white-baikal",
        "board-white-gloss",
        "board-cashmere-front",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "hardware": {
      "label": "Ручки",
      "targets": [],
      "defaultFinish": "metal-black-matte",
      "allowedFinishes": [
        "metal-black-matte",
        "metal-white-matte",
        "metal-anthracite",
        "metal-brass-satin"
      ]
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
