// Generated by assets/source/wardrobes-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "wardrobe-09-chelsea-two-door",
  "label": "Двухдверный шкаф «Челси»",
  "modelUrl": "/models/wardrobe-09-chelsea-two-door.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 0.802,
      "min": 0.6,
      "max": 1,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 2.022,
      "min": 1.9,
      "max": 2.4,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.514,
      "min": 0.4,
      "max": 0.65,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "category": "wardrobes",
  "description": "Размеры корпуса меняются с сохранением толщины панелей.",
  "interiorView": {
    "hiddenNodes": [
      "Door_Left_Hinge",
      "Door_Right_Hinge"
    ]
  },
  "framing": {
    "width": 1,
    "height": 2.4,
    "depth": 0.65
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и полки",
      "targets": [],
      "defaultFinish": "board-grey-chelsea",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-grey-chelsea",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "hardware": {
      "label": "Цвет фурнитуры",
      "targets": [],
      "defaultFinish": "metal-black-matte",
      "allowedFinishes": [
        "metal-black-matte",
        "metal-white-matte",
        "metal-anthracite"
      ]
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
