// Generated by assets/source/wardrobes-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "wardrobe-09-chelsea-two-door",
  "label": "Двухдверный шкаф «Челси»",
  "modelUrl": "/models/wardrobe-09-chelsea-two-door.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 0.802,
      "min": 0.6,
      "max": 1,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 2.022,
      "min": 1.9,
      "max": 2.4,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.514,
      "min": 0.4,
      "max": 0.65,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Door_Left_Hinge",
      "target": "Door_Left_Hinge",
      "label": "Левая дверь",
      "kind": "door",
      "angle": -105
    },
    {
      "id": "Door_Right_Hinge",
      "target": "Door_Right_Hinge",
      "label": "Правая дверь",
      "kind": "door",
      "angle": 105
    }
  ],
  "category": "wardrobes",
  "description": "Размеры корпуса меняются с сохранением толщины панелей.",
  "interiorView": {
    "hiddenNodes": [
      "Door_Left_Hinge",
      "Door_Right_Hinge"
    ]
  },
  "framing": {
    "width": 1,
    "height": 2.4,
    "depth": 0.65
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и полки",
      "targets": [],
      "defaultFinish": "board-grey-chelsea",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-grey-chelsea",
      "allowedFinishes": [
        "board-grey-neutral",
        "board-grey-cool",
        "board-grey-chelsea",
        "board-white-matte",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black",
        "board-muted-green",
        "board-powder-beige"
      ]
    },
    "hardware": {
      "label": "Цвет фурнитуры",
      "targets": [],
      "defaultFinish": "metal-black-matte",
      "allowedFinishes": [
        "metal-black-matte",
        "metal-white-matte",
        "metal-anthracite"
      ]
    }
  },
  "facades": {
    "defaultStyle": "smooth",
    "styles": [
      "smooth",
      "frame",
      "fluted",
      "fluted-sides",
      "diagonal",
      "herringbone"
    ],
    "targets": [
      {
        "panel": "Door_Left_Panel",
        "width": {
          "base": 0.397,
          "dimension": "width",
          "factor": 0.5
        },
        "height": {
          "base": 1.933,
          "dimension": "height",
          "factor": 1
        },
        "thickness": 0.016
      },
      {
        "panel": "Door_Right_Panel",
        "width": {
          "base": 0.397,
          "dimension": "width",
          "factor": 0.5
        },
        "height": {
          "base": 1.933,
          "dimension": "height",
          "factor": 1
        },
        "thickness": 0.016
      }
    ],
    "materialSlot": "fronts",
    "bevel": 0.0007,
    "frame": {
      "width": 0.045,
      "depth": 0.003,
      "slope": 0.002,
      "minField": 0.04
    },
    "fluted": {
      "pitch": 0.02,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "fade": 0.003
    },
    "diagonal": {
      "pitch": 0.08,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "minLength": 0.024
    },
    "herringbone": {
      "pitch": 0.08,
      "width": 0.006,
      "depth": 0.0015,
      "margin": 0.018,
      "endMargin": 0.02,
      "minLength": 0.024,
      "centerGap": 0.012
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
