// Generated by assets/source/dressers-integration/generate_runtime.py
import type { FurnitureDefinition } from '../../furniture/types'

export const catalogue: FurnitureDefinition = {
  ...{
  "id": "dresser-12-brooklyn-six-drawer",
  "label": "Комод «Бруклин»",
  "modelUrl": "/models/dresser-12-brooklyn-six-drawer.glb",
  "dimensions": {
    "width": {
      "label": "Ширина",
      "base": 1.6,
      "min": 1.2,
      "max": 2,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "height": {
      "label": "Высота",
      "base": 0.68,
      "min": 0.55,
      "max": 0.9,
      "step": 0.001,
      "displayUnit": "mm"
    },
    "depth": {
      "label": "Глубина",
      "base": 0.45,
      "min": 0.35,
      "max": 0.6,
      "step": 0.001,
      "displayUnit": "mm"
    }
  },
  "dimensionOrder": [
    "width",
    "height",
    "depth"
  ],
  "articulations": [
    {
      "id": "Drawer_03_Assembly",
      "target": "Drawer_03_Assembly",
      "label": "Левый ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_02_Assembly",
      "target": "Drawer_02_Assembly",
      "label": "Левый ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_01_Assembly",
      "target": "Drawer_01_Assembly",
      "label": "Левый ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_06_Assembly",
      "target": "Drawer_06_Assembly",
      "label": "Правый ящик 1 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_05_Assembly",
      "target": "Drawer_05_Assembly",
      "label": "Правый ящик 2 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    },
    {
      "id": "Drawer_04_Assembly",
      "target": "Drawer_04_Assembly",
      "label": "Правый ящик 3 сверху",
      "kind": "drawer",
      "travel": {
        "dimension": "depth",
        "baseLength": 0.38,
        "factor": 1,
        "ratio": 0.55,
        "max": 0.18
      }
    }
  ],
  "category": "dressers",
  "description": "Размеры комода меняются с сохранением толщины панелей и зазоров ящиков.",
  "framing": {
    "width": 2,
    "height": 0.9,
    "depth": 0.6
  },
  "resizeRules": [],
  "textureAxes": {},
  "materialSlots": {
    "carcass": {
      "label": "Корпус и внутренние детали",
      "targets": [],
      "defaultFinish": "board-white-brooklyn-body",
      "allowedFinishes": [
        "board-white-brooklyn-body",
        "board-cashmere-body",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "fronts": {
      "label": "Фасады",
      "targets": [],
      "defaultFinish": "board-white-gloss",
      "allowedFinishes": [
        "board-white-gloss",
        "board-cashmere-front",
        "board-white-matte",
        "board-grey-neutral",
        "board-graphite-matte",
        "oak-natural",
        "oak-grey",
        "oak-silver",
        "oak-black"
      ]
    },
    "hardware": {
      "label": "Ручки",
      "targets": [],
      "defaultFinish": "metal-white-matte",
      "allowedFinishes": [
        "metal-white-matte",
        "metal-black-matte",
        "metal-anthracite",
        "metal-brass-satin"
      ]
    }
  }
},
  loadRuntime: () => import('./runtime').then(module => module.definition),
}
